### ISSUE TITLE
Camera manager not initialized! Cannot get detectors! 

### ISSUE THREAD

**Issue by r4yfx** [Huddly/sdk#100]
Hi, 

Attempting to gather the detection information from the API and it is advising that the "Camera manager not initialized! Cannot get detectors!"

So l thought that this might be a problem that it hasn't started. It appears that I get a 404 on that page. However, it looks like the API is working properly. As I am receiving data from the info page. Can anyone assist as where I am going wrong? 

Thanks

**Comment by jontore** [comment]
Hi, it that example that probably means you haven't started the detector yet. Before you can get detections with ```GET detector/detections``` you have to start the detector with a ```PUT to detector/start ``` curl -X PUT http://localhost:8080/detector/start```.

**Comment by r4yfx** [comment]
Hi Jontore

Thanks for the response. I though that as well but receiving a '404' on that page

**Comment by jontore** [comment]
If you do a GET (open it a web browser) you get a 404 since it does not support that HTTP verb, you have to to a PUT, which you can do with a js (for example open console in your browser ```fetch('http://localhost:8080/detector/start', {method: 'PUT'})``` https://developers.google.com/web/tools/chrome-devtools/console/javascript) call or a curl command. 

if you're not familiar with HTTP verbs you can read some more about it here. https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

**Comment by r4yfx** [comment]
I am more than positive that I am doing a PUT on the API  (using postman).

**Comment by jontore** [comment]
Great. Interesting I got the following to work with postman..

```
GET http://localhost:8080/info

{
    "id": 10001,
    "serialNumber": "Not found",
    "productId": 33,
    "version": "1.2.16-38450",
    "softwareVersion": "HuddlyIQ-1.2.16-38450",
    "uptime": 76.76,
    "autozoom": {
        "active": true,
        "timestamp": 46390546031
    }
}
```


```
PUT http://localhost:8080/detector/start

{
    "status": "Autozoom started!"
}

```

```
GET http://localhost:8080/detector/detections

{
    "detections": {},
    "framing": {}
}

```

What version of the camera sw are you running. Could you paste the output from ```GET http://localhost:8080/info
```

**Comment by r4yfx** [comment]
ok, thanks for that jontore. 

It appears then that this problem is surely local. I'll nuke and start again and see what happens. Thanks for your help
