### ISSUE TITLE
Is AutoFraming ON or OFF ?

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#104]
How can one read current settings for autoFraming? Using Huddly SDK I can set its value to ON or OFF as desired. But when I detach and attach back the HuddlyIQ, my app does not know current settings for autoFraming.  You have an app (Huddly IQ app version 2.0.27) that displays Auto is ON or OFF. How does it do?

**Comment by brikendr** [comment]
Hi qmas,

You can try using the `getState` method which is part of the IDeviceManager instance. Check out the documentation [here](https://developer.huddly.com/interfaces/IDeviceManager.html#getState) (The method description is a bit misleading, i will fix that very soon). This method will give you information in the following format:
```
{
  status: 0,
  string: 'Autozoom loaded ok',
  autozoom_enabled: true
}
```
On the Huddly App we are using this method to determine whether autozoom is enabled or disabled.

**Comment by brikendr** [comment]
@qmas 

Did the comment help resolving your issue?

**Comment by qmas** [comment]
Sorry, I have not tried yet. I will verify it ASAP then update

**Comment by qmas** [comment]
Yes the method getState works. You can close it now. 
Thanks
