### ISSUE TITLE
Serial can be set to LIBUSB_ERROR_CODE if fails

### ISSUE THREAD

**Issue by jontore** [Huddly/sdk#115]
This can result in serial number being set to the libusb_error_string returned from  ```maybe_get_string```

https://github.com/Huddly/device-api-usb/blob/master/cpp/usb_worker.cpp#L84

https://github.com/Huddly/device-api-usb/blob/9e2768bf3e5feac5529ab76273965965f171a2d9/cpp/usb_worker.cpp#L174

**Comment by jontore** [comment]
@brikendr Is this fixed now

**Comment by brikendr** [comment]
@jontore not sure. I believe not.

**Comment by warddebecker** [comment]
I am getting this error now after updating the firmware on the huddly IQ and upgrading to the latest SDK. How is this an open issue since may 2019??

**Comment by jontore** [comment]
Hi @wdbprog. Are you getting a ```LIBUSB_ERROR```  code when you're running the SDK.

Or are you getting wrong information when you run ```cameraManager.getInfo()``` Which is what this bug is on. That under certain condition the serialNumber property can be read wrong. This is why the we've given the issue low priority.

If you provide us with the camera sw and SDK version you're running we're happy to help resolving your issue.

**Comment by wdbprog** [comment]
@jontore Hello, thanks for the quick response. 
I just updated to the latest SDK  V0.4.1
Camera is on FW 1.3.16-74598

I get the error with the basic people counting example.
Not specifically from the `.getInfo()`

**Comment by jontore** [comment]
Then it is most likely because another application is holding the usb resource, resulting a ```LIBUSB_ERROR_ACCESS ``` error this could be the Huddly App, or another application that is using the SDK.

**Comment by jontore** [comment]
For information, looks like the issue was that the huddly app was running at the same time.
