### ISSUE TITLE
Detecting Head count with Camera not streaming

### ISSUE THREAD

**Issue by qzzf1w** [Huddly/sdk#153]
I was of the understanding that head count was available even if an app wasn't currently accessing the UVC feed.

In my sample app this doesnt seem to be the case.

I can only get the head count Detections event when an app is viewing the feed and the light is on.

**Comment by jontore** [comment]
Hi @qzzf1w. At the moment you have to start streaming to get detections, but this is something that we want to change, and is on the plan for upcoming releases.
