### ISSUE TITLE
Determining if Actively Detecting 

### ISSUE THREAD

**Issue by qzzf1w** [Huddly/sdk#155]
Given that detection is only available if the camera is streaming.

I am wondering how I can detect if/when the camera streaming changes.

For example in your rest example. 

Start detecting without viewing camera stream and it gives me a null for the detections.
Great!
Start streaming the camera and it give me headcount of 1.
Great!
Stop streaming the camera and it still gives me a headcount of 1.
Woops.

I would like to be able to detect if the camera is streaming so that I can qualify the head count value.

How can I do this?

**Comment by jontore** [comment]
One way of doing this would be to use an interval/timer to null out the detectorObj.

In the REST example the detections are cached so you can fetch the last detection from ```/detector/detections```. However it is never reset, a simple way to do this would be to start a resetTimer when you get a new detection

```
let resetDetectorTimer;
 detector.on('DETECTIONS', (d) => {
    detectorObj = d;
    clearTimeout(resetDetectorTimer);
    resetDetectorTimer = startTimeout(() => detectorObj = [], 2000);
  });

```

You should get a new detection every second or so, so this way when the streaming stops and there is no more detections,  the ```/detector/detections``` endpoint will return a nulled detection.

But getting streaming state is definitely something we'll add to our feature request list, it would make this a bit neater.
