### ISSUE TITLE
Some questions about using the API

### ISSUE THREAD

**Issue by AgileTerence** [Huddly/sdk#169]
1. Do you have any plans to develop APIs on the Visual Studio platform? (C++ or C# language) 
2. When does Huddly API support getting the PeopleCounting length without opening a camera application?  
3. How many persons can be detected by Huddly IQ? Depended on system performance?

**Comment by jontore** [comment]
1) At the moment we don't have a C++ ar C# implementation of the sDK
2) This is in the pipeline we can't tell you exactly when, but soon.
3) That depends on how far away the person is and how many can fit in the field of view. There is a hard limit at 100 detections per image, but it depends on the scene.

**Comment by AgileTerence** [comment]
Thank you for your reply. 
In addition, do you have plans to release the API about updating the firmware by programming?

**Comment by brikendr** [comment]
@AgileTerence could you please give us more context of what you mean by `updating the firmware by programming`? Do you mean a firmware upgrade using the SDK?

**Comment by AgileTerence** [comment]
@brikendr  Yes, we can use the SDK to update the firmware. it's helpful for us to integrate into a single application.

**Comment by brikendr** [comment]
@AgileTerence the Huddly SDK has the capability for software upgrades, however, you need a specific formware file which the SDK uses to upgrade the camera. Unfortunately, there is no proper way of distributing such files to the public yet, but we will put this into our agenda and come up with a solution (most likely through the SDK). Thank you for submitting your questions.

**Comment by AgileTerence** [comment]
@brikendr Thanks for your reply.
In addition, Hammer mentioned  C# has supported on Huddly API. Could you have sample code to control HuddlyIQ on C# project?

**Comment by brikendr** [comment]
@AgileTerence 
There is no official support of Huddly SDK for C# at the moment. However, it is possible to integrate your C# application with the nodejs SDK [REST API example](https://developer.huddly.com/additional-documentation/rest-api.html) we have made available for you to test out. This is most likely what Hammer meant by saying that C# is supported with Huddly SDK.

In addition, as you might have noticed we have merged some pull requests that answer some of your original questions submitted in this issue. The new features include:

1. We have added support for getting detections from the Huddly SDK without having to stream your Huddly IQ on you host machine. Please see [Detector.md](https://github.com/Huddly/sdk/blob/master/src/interfaces/IDetector.md)
2. We have also added support of getting the url of the latest Huddly firmware release for both GO and IQ products. You can then use the SDK for performing software upgrades after you have downloaded the firmware from the retrieved URL.

**NOTE:** The first feature can only be used on the next firmware release which most likely will be 1.3.8

**Comment by AgileTerence** [comment]
@brikendr Awesome!!! I can test the REST API example via C#/
Regarding the 2 new features. I will test after the latest firmware(1.3.8) updated. 
Thanks for your kindly support.

**Comment by brikendr** [comment]
@AgileTerence Please note that due to some delays in getting in the new feature on the firmware side and some technical difficulties, 1.3.8 will not include the new feature. Unfortunately you have to wait till next release is available.
I will make sure to update you on which specific firmware version contains the new feature we mentioned.

Thank you for your understanding

**Comment by AgileTerence** [comment]
@brikendr  ok, got it. Look forward the next firmware, thanks.
