### ISSUE TITLE
Full camera sensor resolution snapshot

### ISSUE THREAD

**Issue by asbe** [Huddly/sdk#189]
Is there any pathway for requesting a full sensor resolution image through the SDK, or would this affect the lower level video transport layer?

**Comment by jontore** [comment]
No that is not supported by the SDK.

**Comment by FreedCapybara** [comment]
Hello, are you saying full resolution images aren't supported, or that the SDK doesn't support anything like cameraManager.takePicture()?

If the SDK doesn't support that, is there any way to get an image from the camera?

**Comment by FreedCapybara** [comment]
As a note, after trying a bunch of Python examples, it appears the camera does not function as a normal webcam, unless I'm missing a driver or something.

For example, this page does not capture images with only a Huddly camera connected, but it does work on a computer with a webcam:
https://googlechrome.github.io/samples/image-capture/grab-frame-take-photo.html

**Comment by asbe** [comment]
Hm. @FreedCapybara the snippet you pasted works on my setup ( I have an IQ, and a couple of Go)  - and the Huddly camera behaves (mostly) like any other UVC device in Python - quickest way to access image data would be the capture pipe from OpenCV. What I asked for was if there is any way to get the sensor data (16MP, not rectified) through the SDK.

**Comment by jontore** [comment]
@FreedCapybara Getting video through ```getUserMedia``` should work, you can test out different variation of it here. https://webrtc.github.io/samples/. And the camera support standard UVC, as @asbe mentioned. 

Regarding getting sensor data it is currently not supported, but we can add it to wanted feature list.

**Comment by FreedCapybara** [comment]
Thanks 👍 

Unfortunately I'm still having issues with this, but I'll make a separate question.

**Comment by FreedCapybara** [comment]
When I capture an image using a Huddly camera, the image resolution is 640x360, even though the below code specifies 1920x1080. Is 640x360 the max for the Huddly camera, or is there a way to get higher-resolution captures?

The code, unaltered from #190 
```
from imutils.video import VideoStream
import cv2

# Using src=0 since Huddly IQ is the only camera connected to the host machine
vs = VideoStream(src=0, resolution=(1920, 1080)).start()

frame = vs.read()
cv2.imwrite('test.jpg', frame)
```

The same code produces a 1920x1080 image if we use the source for the non-Huddly camera in our solution.

**Comment by asbe** [comment]
This is default behavior on the Huddly cameras, I believe. You should get
full resolution by setting 'vs. set(cv2.CAP_PROP_FRAME_WIDTH, 1920)'

man. 21. okt. 2019, 16:49 skrev Andrew Temple <notifications@github.com>:

**Comment by FreedCapybara** [comment]
I've tried something like this, but
```py
vs = VideoStream(src=1, resolution=(1920, 1080)).start()
vs.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
```
gives me
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    vs.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
AttributeError: 'WebcamVideoStream' object has no attribute 'set'
```

The following runs okay, but the resulting image is still 640x360:
```py
vs = VideoStream(src=1, resolution=(1920, 1080)).start()
vs.stream.set(cv2.CAP_PROP_FRAME_WIDTH, 1920) # note the vs.stream
```

Various combinations don't seem to work, either
```py
vs = VideoStream(src=1, resolution=(1920, 1080))
# or vs = VideoStream(src=1, resolution=(1920, 1080)).start()
vs.stream.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
# or vs.set(...)
# or vs.stream.stream.set(...)
vs.start() # error
# running those after start() doesn't work either
```

**Comment by bendikhk** [comment]
This seems to be an issue with imutils. VideoStream does not use the resolution provided in the constructor, and vs.stream.set does not work properly. (My guess would be the threading) I was able to reproduce this issue with multiple other cameras, so it is not related to the IQ. You would have to raise this issue with the imutils developers.

However you can read frames from the camera with cv2.VideoCapture directly.
```
import cv2

stream = cv2.VideoCapture(0)
stream.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
stream.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)

for x in range(100):
	valid, frame = stream.read()
	if not valid:
	    break
	print(x, frame.shape)

cv2.imwrite('test.jpg', frame)
stream.release()

#Output
0 (1080, 1920, 3)
1 (1080, 1920, 3)
2 (1080, 1920, 3)
3 (1080, 1920, 3)
4 (1080, 1920, 3)
5 (1080, 1920, 3)
...
```

**Comment by FreedCapybara** [comment]
That's looking better, thanks! Must be that it was always capturing the camera's default resolution.

Is it possible to take 4k captures? Based on the second comment to this thread I'm guessing not. It also looks like the camera only supports a 1080p video stream, which is probably what we're reading from and would explain getting a 1920x1080 image with FRAME_WIDTH=3840.

**Comment by jontore** [comment]
Great, At the moment we don't support 4k captures.
