### ISSUE TITLE
People Count always changes autozoom_enable to true ?

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#199]
Using Huddly app I changed HuddlyIQ autozoom to false (unchecked). Ran my code snippet bellow. When the code ran and people count worked, I noticed that  autozoom has turned to true because the camera was zooming in and out. Using Huddly app I verified that camera has checked autozoom. My question is: **does the people count work only when camera has autozoom enable?**
```

await sdk.init();

sdk.on('ATTACH', async (cameraManager) => {
	const a = await cameraManager.getInfo().then((response) => {
		console.log(response);
		}); // getInfo

	const b = await cameraManager.getState().then((response) => {
		console.log(response);	
		}); // getState

		const detector = cameraManager.getDetector({ shouldAutoFrame: false });
		try {
			const c = await detector.on('DETECTIONS', _.throttle(detections => {
				console.log('People count ', detections.length);
			}, 5000));
			}
		catch (e) {
			console.log(e);
		}

```
Using:
HuddlyIQ-1.3.9-63637
"@huddly/device-api-usb": "^0.1.5",
"@huddly/sdk": "^0.1.16",
Node 8.11.2

**Comment by jontore** [comment]
Hi @qmas, thank you, that is a good question and that  should work.

HuddlyIQ-1.3.9-63637
"@huddly/device-api-usb": "^0.2.9",
 "@huddly/sdk": "^0.3.1",

I made an example where you can turn Az on off persistently and still get detections. However I recognise that this is not as straight forward as it should. The good news is that a new version is coming soon that is cleaning this up a bit.

```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

// Create instances of device-apis you want to use
const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi);

sdk.on('ATTACH', async (cameraManager) => {

	const detector = cameraManager.getDetector({ shouldAutoFrame: false });
	try {
		detector.init();
		const c = await detector.on('DETECTIONS', detections => {
			const people = detections.filter(({ label }) => label === 'person');
			console.log('People count ', people.length);
		});
	} catch (e) {
		console.log(e);
	}

	detector.start();

	let isAutoFraming = false;
	setInterval(async () => {
		const detector = cameraManager.getDetector({ shouldAutoFrame: isAutoFraming });
		await detector.init();
		if (isAutoFraming) {
			console.log('-------------- AUTOFRAME ON --------------------');
			await detector.enable();
		} else {
			console.log('-------------- AUTOFRAME OFF --------------------');
			await detector.disable();
			await detector.start();
		}
		await new Promise(res => setTimeout(res, 4000));
		const b = await cameraManager.getState();
		console.log(b);
		isAutoFraming = !isAutoFraming;
	}, 60000);
});


sdk.init();

```

**Comment by qmas** [comment]
It works fine if I use HuddlyIQ-1.3.9-63637. But may have issues if I use a HuddlyIQ-1.3.4-58795 then the code breaks downs upon usb cable detach/attach. Which SDK version should I use if I am interested in controling HuddlyIQ-1.3.4-58795 ?

**Comment by jontore** [comment]
Hi, it should work fine with  HuddlyIQ-1.3.4-58795 (I was not able to reproduce it). What type of error do you get on attach/detach?

A heads up is that this API will change in the next version of the SDK 0.4 and from next version of the camera sw. 

However I found a bug when attaching missing a ```await detector.init();```

And need to  clear the interval on DETACH

```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

// Create instances of device-apis you want to use
const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi);
let intervalID;

sdk.on('ATTACH', async (cameraManager) => {
	const detector = cameraManager.getDetector({ shouldAutoFrame: false });
	try {
		await detector.init();
		const c = await detector.on('DETECTIONS', detections => {
			const people = detections.filter(({ label }) => label === 'person');
			console.log('People count ', people.length);
		});
	} catch (e) {
		console.log(e);
	}

	detector.start();

	let isAutoFraming = false;
	intervalID = setInterval(async () => {
		const detector = cameraManager.getDetector({ shouldAutoFrame: isAutoFraming });
		await detector.init();
		if (isAutoFraming) {
			console.log('-------------- AUTOFRAME ON --------------------');
			await detector.enable();
		} else {
			console.log('-------------- AUTOFRAME OFF --------------------');
			await detector.disable();
			await detector.start();
		}
		await new Promise(res => setTimeout(res, 4000));
		const b = await cameraManager.getState();
		console.log(b);
		isAutoFraming = !isAutoFraming;
	}, 60000);
});


sdk.on('DETACH', () => {
	clearInterval(intervalID);
});


sdk.init();
```

**Comment by qmas** [comment]
1.  There is an issue running my code for the following camera: if I run my application with autoZoom true then run again with false. Error file is attached
HuddlyIQ-1.3.11-63637
"@huddly/device-api-usb": "^0.2.9",
"@huddly/sdk": "^0.3.1",
[Huddly IQ1.3.11.txt.txt](https://github.com/Huddly/sdk/files/3718224/Huddly.IQ1.3.11.txt.txt)

2. I see No issue for the following camera. I can plug/unplug camera, or change autozoom true to false or false to true still no issue 
HuddlyIQ-1.3.9-63637
"@huddly/device-api-usb": "^0.2.9",
"@huddly/sdk": "^0.3.1",

**Comment by jontore** [comment]
Hi, great thank you. With 1.3.11 it can look like the detector is not ready when you enable autoZoom.  Since this is the RC candidate at the moment it has some changes to how you enable/disable detector, from this version you can also get detections without streaming video. 

You can either wait until monday for the new SDK release 0.4, which has a few changes to how you control auto zoom and the detector. Which will make things a bit simpler, or you can use master from the sdk.

Change your dependency in the package.json  to 

```
"@huddly/sdk": "git+ssh://git@github.com:Huddly/sdk.git"
```

This example shows how this will work with the latest sdk changes, works with 1.3.11 on attach detach.
Here you can see that controlling of genius framing and detections are split up, so no need to get a new detector when you want detections with genius framing off. 
 
```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

// Create instances of device-apis you want to use
const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi);

sdk.on('ATTACH', async (cameraManager) => {
	const detector = cameraManager.getDetector();
	// const autozoomCtl = cameraManager.getAutozoomControl();
	try {
		// Make sure that autozoom (genius framing is started)
		// await autozoomCtl.init();
		// await autozoomCtl.start();
                // To stop it again
		// await autozoomCtl.stop();

		await detector.init();
		const c = await detector.on('DETECTIONS', detections => {
			const people = detections.filter(({ label }) => label === 'person');
			console.log('People count ', people.length);
		});
	} catch (e) {
		console.log(e);
	}
});

sdk.init();```


The error with 1.3.4 I could not reproduce the error with this snippet.
```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

// Create instances of device-apis you want to use
const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi);

sdk.on('ATTACH', async (cameraManager) => {
	const detector = cameraManager.getDetector({ shouldAutoFrame: false });
	try {
		await detector.init();
		await detector.disable();
		await detector.start();
		const c = await detector.on('DETECTIONS', detections => {
			const people = detections.filter(({ label }) => label === 'person');
			console.log('People count ', people.length);
		});
	} catch (e) {
		console.log(e);
	}
});

sdk.init();````

Hope that helps, sorry for the confusion with 1.3.11, since it is RC it is no compatible with the latest SDK. We're making sure stable camera sw is compatible with latest SDK.

**Comment by qmas** [comment]
Hi Jontore, I will wait for your next SDK release, don't rush for us because I have a workable solution for the issue 1 describe in https://github.com/Huddly/sdk/issues/199#issuecomment-541101245 . I commented out the following code lines. As a result now Peopl Count works with autoFraming true or false and also works for camera unplug and plug back use cases. 
```
/*if (isAutoFraming) {
			await detector.enable();
		} else {
			await detector.disable();
			await detector.start();
		}
}*/
```

**Comment by jontore** [comment]
Great, I'll update this issue when the release is it stayed tuned for an update on 1.3.11.

**Comment by jontore** [comment]
@qmas 0.4.0 is now available and is compatible with 1.3.11. But as described before it changes the behaviour how you control detector and autozoom making it easier.

**Comment by jontore** [comment]
Here is in an updated example turning Genius Framing on/off while getting detections for the new sdk 0.4.0 and the 1.3.11. One thing to note is that now as with previous software detections include people and heads, so you need to filter for that if you only want people detections. 

```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

// Create instances of device-apis you want to use
const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi);
let intervalID;

sdk.on('ATTACH', async (cameraManager) => {
	const detector = cameraManager.getDetector();
	const autozoomCtl = cameraManager.getAutozoomControl();
	try {
		// Make sure that autozoom (genius framing is started)
		await autozoomCtl.init();
		await detector.init();

		await detector.on('DETECTIONS', detections => {
			const people = detections.filter(({ label }) => label === 'person');
			console.log('People count ', people.length);
		});
	} catch (e) {
		console.log(e);
	}

	let isAutoFraming = false;
	intervalID = setInterval(async () => {
		// To stop it again
		if (isAutoFraming) {
			console.log('-------------- AUTOFRAME ON --------------------');
			await autozoomCtl.start();
			//To persistently turn it on
			await autozoomCtl.enable();
			process.exit();
		} else {
			console.log('-------------- AUTOFRAME OFF --------------------');
			await autozoomCtl.stop();
			//To persistently turn it off
			await autozoomCtl.disable();
		}
		const b = await cameraManager.getState();
		console.log(b);
		isAutoFraming = !isAutoFraming;
	}, 20000);
});


sdk.on('DETACH', () => {
	clearInterval(intervalID);
});


sdk.init();
```

**Comment by qmas** [comment]
Updated to sdk 0.4.0 and tried people count. People count works. But I noticed that the light of the camera is always ON. The only time it goes off is when my application is stopped. I thought light should only be on when video is on. Is this expected from this sdk 0.4.0 ?

**Comment by jontore** [comment]
Yes it is on as long as video is streaming, if it used for detections or for a VCA. To turn the led off you need to stop the detections.

**Comment by qmas** [comment]
Currently I run application, do people count, then kill application to end running. How can I end my application gracefully so that first streaming stopped then application is terminated?

**Comment by jontore** [comment]
You need to destroy the detector before you close the process something like this

```
		await detector.destroy();
		process.exit();
```

**Comment by qmas** [comment]
Jon, the problem is a parent application starts HuddlyIQ.exe and stops it (by taskkill windows command) whenever it wants. There is no mechanism that allows the parent application to communicate with HuddlyIQ.exe. Prior to sdk 0.4.0 our needs were met without communicating with HuddlyIQ.exe. 
With the new sdk if parent application have to communicate with HuddlyIQ.exe then we will. But I will prefer if we can work without communicating with HuddlyIQ.exe just as we were in sdk 0.3.1.

**Comment by jontore** [comment]
I see, the consequence is then that the light is left on, since there is no way for the camera to know that you're no longer getting detections.

**Comment by qmas** [comment]
I guess you are right. But as I pointed out your earlier sdk 0.3.1 handled it very well, when there is no video there should be no light or people counting.

**Comment by jontore** [comment]
I'll look into what can be changed there. Being able to get detections without the video stream is a feature we've been working on get in, but maybe there should be an option. That is good input, let me check in with the team and see if that is a possibility.

**Comment by qmas** [comment]
Ok thanks. Yes such an option will help.

**Comment by jontore** [comment]
Good news turns out this is already an option, my bad missing that.

```  cameraManager.getDetector({ DOWS: true });``` and the behaviour should be the same in 0.3.1

**Comment by FreedCapybara** [comment]
`DOWS: true` and `DOWS: false` both seem to require a video stream to process detections. Am I doing something wrong?

```js
      const autozoomCtl = cameraManager.getAutozoomControl();
      // Make sure that autozoom (genius framing is started)
      await autozoomCtl.enable();
      await autozoomCtl.init();
      await autozoomCtl.start();

      // Now get the detector instance from sdk
      const detectorOpts = {
        DOWS: true, // DOWS = 'detection only when streaming' (per the docs)
        objectFilter: ['head', 'person']
      };
      const detector = cameraManager.getDetector(detectorOpts);

      // Setup the detection listener
      detector.on('DETECTIONS', detections => {
        // ...
      });
```

**Comment by brikendr** [comment]
@FreedCapybara Please verify that your camera is running version 1.3.11 of the camera firmware! Older versions do not support detections without streaming, therefore `DOWS` option does not work.

`DOWS` options is default `false` which means that you are not required to start a video stream on your host in order to get detection data (Note, always gracefully shutdown the detector by calling `destroy` method on it as not doing so will leave the camera streaming internally and generating detection events until reboot). Setting `DOWS` to `true` has the oposite effect (same as sdk versions before 0.4.0)

Here is a camera info json output for reference:
```
{
 "id": "IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@01000000/Huddly IQ@01230000",
 "serialNumber": "B40H00019",
 "vendorId": 11225,
 "productId": 33,
 "version": "1.3.11-66298",
 "softwareVersion": "HuddlyIQ-1.3.11-66298",
 "uptime": 84.93,
 "pathName": "IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@01000000/Huddly IQ@01230000"
}
```
