### ISSUE TITLE
REST server and /detector/detections

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#222]
As directed in #219, I updated sdk and its dependencies. 
Now the `http:/localhost:8080/Info` has started working and returns correct response. 
But the `http:/localhost:8080/detector/detections` still returns the `{"error":"Camera manager not initialized! Cannot get detectors!"}`

**Comment by jontore** [comment]
You need to start the detector first, do a PUT to ```detector/start``` https://developer.huddly.com/additional-documentation/rest-api/detector-start.html
