### ISSUE TITLE
When running mouse/keyboard is slow, and speaker crackles

### ISSUE THREAD

**Issue by hroblesm** [Huddly/sdk#251]
When running people count, the following happens:
conference speaker crackles
mouse/keyboard is slow to respond
The problem gets much worse when then speaker/keyboard/mouse are through a USB hub

Huddly is plugged directly into a USB 3 port with the proper huddly cable

Steps to reproduce:
install huddly camera with proper huddly cable directly into a USB3 port 
install a USB speaker into a USB port on the computer
play a song on MP3
start the Huddly demo app and start playing video
move the camera around
speaker crackles
If the spaker and keyboard/mouse are attached to a hub, the mouse movement and key actions will be heavily delayed.

**Comment by jontore** [comment]
Interesting, we'll try to reproduce this issue. Can you please provide some more information about what type of machine and USB hub this is happening on. 

Also operatinst system, camera sw version and SDK.

**Comment by jontore** [comment]
Close due to inactivity
