### ISSUE TITLE
Can't get absolute position values for current frame.

### ISSUE THREAD

**Issue by donte525** [Huddly/sdk#298]
The BBox coordinates received from detection events seem to always return full field of view values. I tried copying the code from the FAQ that relates to the problem  but the values remain unchanged when autozooming occurs. This is with the Huddly IQ version 1.3.16-74598. Below is the relevant code sample.

```
let cameraManagerVariable;

async function init() {
    await sdk.init();

    sdk.on('ATTACH', async (cameraManager) => {
        //Store the camera manager once a huddly camera has been connected 
        cameraManagerVariable = cameraManager;
        autozoomctrl = cameraManager.getAutozoomControl();
        // Make sure that autozoom (genius framing is started)
        await autozoomctrl.init();
        await autozoomctrl.start();

        // Now get the detector instance from sdk
        const detector = cameraManager.getDetector({ convertDetections: 'FRAMING' });

        // Setup the detection listener
        detector.on('DETECTIONS', detections => {
		
            console.log('Stuff Detected ', detections);	
            recentPeopleDetections = detections;

        });

        // Calling detector init will initiate the generation of detection events
        detector.init();

    });
}
init();

```

**Comment by jontore** [comment]
Hi, I think there is a bug here it is necessary to know what frame GF has chosen to get absolute coordinates, this is only possible if ```DOWS: true``` where you get detections when using the main stream. 

Your example should work if you change add this option to  ```const detector = cameraManager.getDetector({ convertDetections: 'FRAMING', DOWS: true });```

**Comment by jontore** [comment]
Close due inactivity
