### ISSUE TITLE
Huddly IQ Lite Support ?

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#315]
I got a prototype camera "Huddly IQ Lite" from my management. This camera works in Windows but Huddly app version 2.0.67 doesn't detect this camera. Does Huddly Sdk supports or do you plane to support this camera for reading firmware version. This camera appears in Windows to have  VID_2BD9&PID_0051.

**Comment by jontore** [comment]
Hi, @qmas. If you shoot me an email at jontore@huddly.com I can give you more details about the unit and the support for it.
