### ISSUE TITLE
underscore package with "@huddly/sdk": "^0.4.2"

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#369]
I want to know if npm package underscore is supported in "@huddly/sdk": "^0.4.2": Please refer the issue "Motion or Face detection #102". To get less events I throttle the detection by using underscore package, like 
`detector.on('DETECTIONS', _.throttle(detections => { console.log('People count ', detections.length); }, 5000));`

Today, when I updated to "@huddly/sdk": "^0.4.2", my code for people count raised exception. 
When I removed _.throttle then I saw no issue, except perhaps more events.

**Comment by jontore** [comment]
Underscore is a library on its own (https://www.google.com/search?q=underscore&oq=under&aqs=chrome.1.69i57j0l2j46j69i65j69i61l3.3261j0j7&sourceid=chrome&ie=UTF-8) so we can not guarantee that it will always work with the SDK. But I don't see why it should not work in this case. What type of exception did you get?

**Comment by qmas** [comment]
Since the latest sdk, when I `npm uninstall underscore` my code runs fine but without throttle.
But when I `npm install underscore`, and run my code, then my code logs the following error:
`(node:27048) UnhandledPromiseRejectionWarning: Error: Cannot find module '@huddly/sdk'
Require stack:
- d:\Work\_CCS\CCS_400_branch_835\HuddlyIQ\people_count2.js
- d:\Work\_CCS\CCS_400_branch_835\HuddlyIQ\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.people_count2 (d:\Work\_CCS\CCS_400_branch_835\HuddlyIQ\people_count2.js:12:23)
    at Object.<anonymous> (d:\Work\_CCS\CCS_400_branch_835\HuddlyIQ\index.js:80:22)
    at Module._compile (internal/modules/cjs/loader.js:1135:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
warning.js:32
(node:27048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
warning.js:32
(node:27048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by jontore** [comment]
Hi, it looks like this has either something to do with an unhandled promise rejection or an error, most likely something with how an async block is being used. 

Sorry for the confusion, but I would recommend using lodash as mentioned in #102. But it should also work with underscore, just a different library where lodash is the more modern and popular of the two (both of them referred to with an _, hence the confusion) 

I tested it and both should work with the latest sdk, and previous here is an example. 

```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;
const _ = require('underscore');

const meetingRoomName = process.env.HUDDLY_MEETING_ROOM || 'TEST_ROOM';
const cameraSerialNumber = process.env.DETECTIONS_SERIAL_NUMBER || 'B41A00826';

const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi);

async function init() {
  await sdk.init();

  sdk.on('ATTACH', async (cameraManager) => {

    const info = await cameraManager.getInfo();

    const detectorOpts = {
        // DOWS: false, // DOWS is default false if set to true you only get detections when streaming video!
    	objectFilter: ['head', 'person']
    };

    const detector = cameraManager.getDetector(detectorOpts);


    detector.on('DETECTIONS', _.throttle(detections => {
      console.log('----------- detections ', detections.length);
    }, 5000));

    // // Calling detector init will initiate the generation of detection events
    await detector.init();

    setTimeout(async () => {
      await detector.destroy();
    }, 4000);
  });
}

init();
```
package.json
```{
  "name": "sdk-test-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@huddly/device-api-usb": "^0.2.14",
    "@huddly/sdk": "^0.5.0",
    "underscore": "^1.10.2"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

Could you try and see if you get this working? Could you provide the code that is running on ```DETECTIONS``` events.

**Comment by qmas** [comment]
Thanks. You can close this issue. 
The underscore worked fine when I used the latest sdk 
`"@huddly/device-api-usb": "^0.2.14",
    "@huddly/sdk": "^0.5.0",`
