### ISSUE TITLE
Is there an API to get firmware versions available for Huddly Cameras ?

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#372]
From the REST server described in the [link](https://developer.huddly.com/additional-documentation/examples/rest-api.html), I see REST API GET /upgrade/status that I assume shows status when upgrade is happening. Is there an API to find out if there is newer firmware avail or not?

**Comment by jontore** [comment]
Hi, @qmas

Yes you're correct, that API endpoint shows you the status of an started upgrade. 

 At the moment there is not a way in the sdk to automatically check for new SW versions. We're working on a solutions to make distributed upgrades available.

**Comment by qmas** [comment]
When I connect camera with older firmware, the Huddly app shows update available. I wonder how the Huddly App on my laptop shows that there is firmware update available?

**Comment by jontore** [comment]
The sdk has a way undocumented method to retrieve  the latest SW pkg url ```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;
const _ = require('lodash');


const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi);

async function init() {
  await sdk.init();

  sdk.on('ATTACH', async (cameraManager) => {

    const d = await cameraManager.getLatestFirmwareUrl();

    console.log(d);
  });
}

init();
```

However it does not expose, or offer a way to compare the version number. We'll take into consideration to create a method that can check the version number on the camera and and compare it to the latest package.

**Comment by qmas** [comment]
Thanks you very much. You may close this issue now
