### ISSUE TITLE
Auto Framing and camera LED light may have an issue with @huddly/sdk": "^0.5.0",

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#374]
Please see the following code snippet . With a previous sdk version this code used to count people and allowed auto framing true or false. Since I upgraded sdk to the latest version, people counting works but auto framing does not work. Also while counting the camera LED light stays on even when video app is not opened. 
I have gone through the issue #199 but can not see whats wrong

     `........
            1. const detector = cameraManager.getDetector({ shouldAutoFrame: true });
			//2. const detector = cameraManager.getDetector({ shouldAutoFrame: false });
            detector.init();
            const c = await detector.on('DETECTIONS', _.throttle(detections => {
                    console.log('People count: ', detections.length);
                }, 5000));

            }
	.........`

Previous sdk: worked for auto framing and LED light
    HuddlyIQ-1.3.28-89114
   "@huddly/device-api-usb": "^0.2.9",
   "@huddly/sdk": "^0.3.1",

Latest sdk: auto framing doe not work and LED light stays on
   HuddlyIQ-1.3.28-89114
   "@huddly/device-api-usb": "^0.2.14",
   "@huddly/sdk": "^0.5.0",

**Comment by jontore** [comment]
Hi qmas if you only want detections when you're streaming video you need to set ```DOWS: true```

As discussed in #199 This default behaviour was changed in 0.4.0, the migration and the changes should be documented on ```developer.huddly.com```


The default behaviour now is that the SDK starts a preview stream be default and gets detections without having to stream video by default. 

There are also some breaking changes to how you enable/disable genius framing, you can check out the documentation here https://developer.huddly.com/interfaces/IAutozoomControl.html#readme

Just let us know if we can assist you more in the migration to newer version of the SDK.

**Comment by qmas** [comment]
Thanks jontore for pointing me to use developer.huddly.com. While we have this issue open, please confirm that I understood the following two items

1. DOWS:true will keep LED off
2. The following code snippet will allow to switch between auto zoom true or false (from issue #199)

if (isAutoFraming) {
    console.log('-------------- AUTOFRAME ON --------------------');
    await detector.enable();
} else {
         console.log('-------------- AUTOFRAME OFF --------------------');
         await detector.disable();
         await detector.start();
}

**Comment by jontore** [comment]
No problem, ```DOWS:true ``` will give you only detections when the video stream is being used by a different application. 

So the LED will be on when for instance Zoom is using the camera, and you'll get detections while the stream is being used. As soon as Zoom stops, the LED will be off, and you'll no longer get detections. 

When it comes to turning genus framing on and off the behaviour has changed in 0.4, this is now controlled through the AutoZoomControl interface https://developer.huddly.com/interfaces/IAutozoomControl.html#readme.

Here is an example getting detections only while streaming in an application, starting by turning Genius Framing on and after 10sek turning it off.  

```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

const meetingRoomName = process.env.HUDDLY_MEETING_ROOM || 'TEST_ROOM';

const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi, [usbApi]);

sdk.on('ATTACH', async (cameraManager) => {
  const autozoomCtl = cameraManager.getAutozoomControl();
  // Make sure that autozoom (genius framing is started)
  await autozoomCtl.init();
  await autozoomCtl.start();

  // Detector options to get head and person detections without streaming main
  const detectorOpts = {
    DOWS: true, // DOWS is default false if set to true you only get detections when streaming video!
    objectFilter: ['head', 'person']
  };

  const detector = cameraManager.getDetector(detectorOpts);

  // Setup the detection listener
  detector.on('DETECTIONS', detections => {
    // detection stuff
    console.log(`Got ${detections.length} detections from camera with serial ${cameraManager.serialNumber}`)
  });

  // Calling detector init will initiate the generation of detection events
  detector.init();

  setTimeout(async () => {

    console.log('Genius framing off');
    await autozoomCtl.stop();
  }, 10000);


  process.on('SIGINT', async () => {
    console.log("\nClosing application gracefully");
    if (detector) {
      console.log('Destroying detector');
      //If you don't destroy the detector correctly the LED on the camera will be left on
      await detector.destroy();
    }

    if (cameraManager) {
      console.log('Closing connection with the camera');
      await cameraManager.closeConnection();
    }
    console.log("\nTeardown completed! Application closed");
    process.exit();
  });
});

sdk.init();

```

**Comment by qmas** [comment]
Nice code snippets, thanks.
Is there a way to detect if video is not playing?

**Comment by jontore** [comment]
No there is not

**Comment by jontore** [comment]
Init/destroy will not change the options. You would have to call ```cameraManager.getDetector``` with new options and reinitialize. 

Like in this example it switches between the modes every 10 seconds

```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi, [usbApi]);

sdk.on('ATTACH', async (cameraManager) => {

  let detector;
  const detectorOpts = {
    DOWS: true, // DOWS is default false if set to true you only get detections when streaming video!
    objectFilter: ['head', 'person']
  };
  setInterval(async () => {
    if (detector) {
      await detector.destroy();
      detectorOpts.DOWS = !detectorOpts.DOWS;
    }

    console.log(`DOWS ${detectorOpts.DOWS}`);

    detector = cameraManager.getDetector(detectorOpts);

    detector.on('DETECTIONS', detections => {
      // detection stuff
      console.log(`Got ${detections.length} detections from camera with serial ${cameraManager.serialNumber}`)
    });

    detector.init();
  }, 10000);


  process.on('SIGINT', async () => {
    console.log("\nClosing application gracefully");
    if (detector) {
      console.log('Destroying detector');
      //If you don't destroy the detector correctly the LED on the camera will be left on
      await detector.destroy();
    }

    if (cameraManager) {
      console.log('Closing connection with the camera');
      await cameraManager.closeConnection();
    }
    console.log("\nTeardown completed! Application closed");
    process.exit();
  });
});

sdk.init();
```
