### ISSUE TITLE
.Net client 

### ISSUE THREAD

**Issue by v-tbert** [Huddly/sdk#375]
Communicating with locally connected devices via node is an unusual requirement. Are there plans to make a sdk for .net?

**Comment by jontore** [comment]
There is not plan for it at the moment, but something we will consider.

**Comment by mjuskiewicz** [comment]
@v-tbert , I had the same problem. I was looking for a .NET version of SDK. Finally I created a nodeJS self contained application and wrapped it in Windows service that can be installed via MSI. For communication you can use NamedPipilines or Rest API. If you have a better solution let me know.
