### ISSUE TITLE
How can I

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#41]
Using Huddly API or SDK, how can one control camera features like Framing and Zoom, Pan, Tilt. Please point me to a sample or code snippet

**Comment by jontore** [comment]
Hi Qmas, right now you can not control zoom, pan, tilt. However the camera is UVC device which means that it can control such properties via UVC controls. We're considering adding such features to the SDK in the future. 

Sorry about that.

**Comment by qmas** [comment]
How about Auto Framing ON/OFF? I will like to turn off auto zoom to a face. Also removing rectangle around the face
