### ISSUE TITLE
SDK-For Android

### ISSUE THREAD

**Issue by sbadoni** [Huddly/sdk#428]
Hello Team,
I would like to know whether HuddlySdk is available for android. As i have seen in path 
"node_modules/@huddly/device-api-usb/lib/prebuilds"  don't have support for android.
Do we need to download prebuilds from some different location?

**Comment by jontore** [comment]
Hi @sbadoni .

I'm sorry to say that the sdk is not available for Android at the moment.

**Comment by sbadoni** [comment]
Thanks @jontore
