### ISSUE TITLE
npm install @huddly/device-api-usb fails with Error 404 while downloading

### ISSUE THREAD

**Issue by vladiso** [Huddly/sdk#429]
https://deviceapiusb.blob.core.windows.net/device-api-usb/node.napi-0.2.15-win32-x64.node - throws Error404

**Comment by jontore** [comment]
Thank you for reporting this @vladiso It should be fixed now. Let me know if you have any more trouble. There is also a new package with a bit broader electron support.

**Comment by vladiso** [comment]
Confirmed. Works Properly now. Thank you!
