### ISSUE TITLE
shouldAutoFrame questions

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#48]
Continue from issue #46 
When are you going to merge the #42 , an estimate of time? How can I update my repo with the changes in #42?

**Comment by brikendr** [comment]
Hi @qmas ,

We have split the #42 PR into two separate PR-s, namely #49 and #50. The changes related to your question are available on #49 and will be merged and released to npm most likely later today.

Will close your issue when we release the new version with the changes of #49 included!

**Comment by brikendr** [comment]
Hi @qmas ,

The SDK version 0.1.12 has been released to npm. This patch includes the aforementioned changes. 

Closing issue!
