### ISSUE TITLE
By default AutoFraming is ON ? 

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#57]
Could you please confirm if by default the AutoFraming is ON or OFF for the camera HuddlyIQ-1.2.9.33901

**Comment by qmas** [comment]
Also please do not close the issue right after your answer, wait until I read and confirm it

**Comment by jontore** [comment]
It is by default off in 1.2.9.33901

**Comment by qmas** [comment]
The HuddlyIQ that I am using has 1.2.9.33901. But it behaves as if autoFraming is ON. The camera zooms in and zooms out automatically when I come close or go away from the camera. Also when a second person walks in the view, the camera zooms out to include the second person. To my understanding if autoFraming is OFF then the camera should not zoom in/out automatically. Please confirm my understanding of autoFramming

**Comment by jontore** [comment]
So in 1.2.9-33901 autoframing is persisted, that means if you turn it on it will be on until you turn it off again, even if you don't have the sdk our the app running.

**Comment by qmas** [comment]
I turned autoFramming OFF. Once camera is detached/attached or laptop power cycles, autoFraming gets turned ON. Its persistent till the camera stays connected. Not sure if it should be called persistent. 

Please confirm: By default the camera has autoFraming ON, SDK allows to turn autoFraming OFF, The auotoFraming will stay OFF until camera is power cycled

**Comment by jontore** [comment]
By default it is off, until you turn it on.

If you power cycle the camera it should be in the same state as it was before you power cycled it. On if it was on, off if it was off.

**Comment by qmas** [comment]
But that is not want I observed. I turned autoFraming OFF using sdk, confirmed it was OFF, then power cycled camera and autoFraming turned ON by itself.  What wrong am I doing ? I know firmware 1.2.9-33901 but could it be camera model/hardware ?
id              =  46763835
vendorId        =  11225
productId       =  33
productName     =  undefined
uptime          =  3294.46
serialNumber    =  B40J00080
version         =  1.2.9-33901
softwareVersion =  HuddlyIQ-1.2.9-33901

**Comment by jontore** [comment]
Hmm, what version of the sdk are you running. 

Could it be that your app turns the detector back on again as soon as the camera attaches?

**Comment by qmas** [comment]
+-- @huddly/sdk@0.1.12

**Comment by qmas** [comment]
My app runs on demand. When I detached and attached back the camera, I never ran my app.

**Comment by jontore** [comment]
That should work with 1.2.9-33901.

I tried to reproduce it locally with this script 

```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

const usbApi = new HuddlyDeviceAPIUSB();
const sdk = new HuddlySdk(usbApi);

async function init() {
  await sdk.init();

  return new Promise((resolve, reject) => {
    const timeoutId = setTimeout(() => reject('NO CAMERA ATTACHED'), 5000);
    sdk.on('ATTACH', async (cameraManager) => {
      clearTimeout(timeoutId);
      const detector = await cameraManager.getDetector();
      await detector.init();

      detector.on('DETECTIONS', detections => {
        console.log(detections);
      });

      detector.start();

      setTimeout(() => {
        console.log('------------ timeoout ----------');
        detector.stop();
      }, 20000)
      resolve();
    });
  });
}

init().catch((e) => {
  console.warn(e);
  process.exit(-1);
});```

and that worked fine.

Detects for 20 seconds then stops, I stoppet the application and power cycled the camera. 

running 0.1.14

**Comment by qmas** [comment]
I am using sdk 0.1.12 and you are 0.1.14. Perhaps update to 0.1.14 will make a difference. Should I update or there is no difference

**Comment by qmas** [comment]
I updated to 0.1.14. Performed the six steps in your comment. The autoFraming was OFF but autoFraming turned ON after camera power cycled.

Please verify the console messages (bellow) coming out of my script and HuddlySDK, espectialy the error messages. Perhaps the Error: LIBUSB_ERROR_NOT_SUPPORTED should not be there. 


```
C:\tmp\Debug400>huddlyIQ.exe autoframe false  30000
[ 'autoframe', 'false', '30000' ]
shouldAutoFrame  false
will wait  30000 sec
C:\Program Files\Crestron\CCS400\User
writeToFile: C:\Program Files\Crestron\CCS400\User\hwSettings\HuddlyIQ.dat
Node-USB Hotplug Events not supported on this machine. Falling back to discovery poll!
{ Error: LIBUSB_ERROR_NOT_SUPPORTED
    at Object.<anonymous> (D:\snapshot\HuddlyIQ\node_modules\usb\usb.js:516:7)
    at emitTwo (events.js:126:13)
    at Object.emit (events.js:214:7)
    at _addListener (events.js:249:14)
    at Object.addListener (events.js:297:10)
    at DeviceDiscoveryManager.registerForHotplugEvents (D:\snapshot\HuddlyIQ\node_modules\@huddly\device-api-usb\lib\src\manager.js:90:27)
    at HuddlyDeviceAPIUSB.registerForHotplugEvents (D:\snapshot\HuddlyIQ\node_modules\@huddly\device-api-usb\lib\src\index.js:29:37)
    at new HuddlySdk (D:\snapshot\HuddlyIQ\node_modules\@huddly\sdk\lib\src\index.js:55:34)
    at Object.autoFrame (D:\snapshot\HuddlyIQ\autoFrame.js:13:17)
    at Object.<anonymous> (D:\snapshot\HuddlyIQ\index.js:40:19) errno: -12 }
:::::::::::: Transport Protocol is HLINK ::::::::::::
before init
Uploading new framing config!
after init
Start cnn enable
ending after  30000 sec
```

**Comment by jontore** [comment]
So @brikendr pointed out to me that I might have misunderstood what you mean. It is only when init is performed that autoframing is turned off, to the degree that detections happen but not framing. 

So that means if you don't perform ```detector.stop``` the camera will go back to detecting with autoframing after a reboot so detection and autoframing if you did a ```detetor.init()``` ```detector.start()``` before the reboot. 

@brikendr Could you elaborate here maybe.

**Comment by qmas** [comment]
My script was not reaching detector.stop(). I ran your code snippet that you posted in a previous comment (above). Now the camera has persistent autoframing OFF as desired. 

But now I cannot turn autoframing ON. I used your code with the following line changed to
`const detector = await cameraManager.getDetector( { shouldAutoFrame: true } );`

**Comment by brikendr** [comment]
Hi @qmas 

It seems that the framing configuration we change by doing `cameraManager.getDetector({ shouldAutoFrame: true/false });` is not persistent, therefore it will fallback to default framing configuration when rebooting the camera (that is auto-framing being enabled).

So on that note, if you want your code to disable auto-framing on the camera, you call the detector init method with the options `{ shouldAutoFrame: false }`, but keep in mind that if the camera restarts, you will have to call the init method on the detector again, with the same options. 

If there is still confusion around this please ask. Just keep in mind that the `shouldAutoFrame` detector initialization option is not persistent on the camera!

**Comment by qmas** [comment]
Yes I verified that `cameraManager.getDetector({ shouldAutoFrame: true/false });` works and is not persistent. 
Jontore in one of his previous comment suggested detector.stop to turned autoframe OFF persistently, I used  detector.stop successfully to put camera autoframe off permanently. Now detach/attach camera and camera keeps autoframing OFF

But now I cannot turn autoframing ON. How to turn autoframing ON again for a camera that has autoframing permanently turned OFF?

**Comment by brikendr** [comment]
In order to make the camera run auto-framing again, all you have to do is:
1. Reboot the camera
2. Re-initialize the detector as in the following snippet:
```
....
const detector = await cameraManager.getDetector();
await detector.init();
await detector.start();
....
```
3. Keep in mind that when calling `getDetector` without any options, the auto-framing options is 'ON' by default!

This should make your IQ camera run auto-framing on the stream and detection data.

**Comment by brikendr** [comment]
@qmas could you please confirm that this issue has been resolved so that we can close it!

Thank you.

**Comment by qmas** [comment]
Yes please you may close this issue for now.
