### ISSUE TITLE
Errors when setting up Huddly SDK for people counting feature

### ISSUE THREAD

**Issue by avassist** [Huddly/sdk#582]
[Huddly SDK errors (1).pdf](https://github.com/Huddly/sdk/files/13990024/Huddly.SDK.errors.1.pdf)

Attached are the errors that I get when setting up a sdk instance using the Node.js v16.20.2. I have highlighted the errors in Red for proper viewing. This shows that once a huddly SDK is not defined then we can't move forward with accessing the people counting feature. 

Is there anything step that I may be missing when setting this up?

**Comment by pkhansen** [comment]
Hi there!
Sorry for the late reply.
I tested with the same node version and did not encounter any issues.
From your attached pdf it seem like the sdk and device apis are missing in the context of your node repl.
Make sure that: 
- You're starting your node repl from a folder where the dependencies are available.
- You haven't forgotten to install the necessary dependencies:
`npm install @huddly/sdk`
`npm install @huddly/device-api-usb`
`npm install @huddly/device-api-ip`
