### ISSUE TITLE
Reading information from Huddly camera with older firmware ?

### ISSUE THREAD

**Issue by qmas** [Huddly/sdk#59]
Using "@huddly/device-api-usb": "^0.1.5", "@huddly/sdk": "0.1.14" , I can read camera information of newer cameras. But my  script does not read camera information for the following camera.  
```
"version":"0.1.0-16997",
"softwareVersion":"HuddlyIQ-0.1.0-16997",
```
I don't want to upgrade the firmware in the camera. Is there any specific sdk version that reads camera information from older camera firmware?

**Comment by jontore** [comment]
This is unfortunately not possible , since so old camera-sw does not support the USB transport.
